[download]
platform                = "SENTINEL-1"
relative_orbit          = 128
start_date              = 20160830
end_date                = 20161031
max_results             = 2000
bounding_box            = "POLYGON((-99.20 19.25, -99.10 19.25, -99.10 19.35, -99.20 19.35, -99.20 19.25))"
parallel_downloads      = 8
burst_download          = false
slc_dir                 = "./SLC"

[dem]
data_source             = "COP"
dem_dir                 = "./DEM"

[isce]
slc_dir = "./SLC"
dem = "./DEM"
#bbox = [-99.20, 19.25, -99.10, 19.35]
start_date = "2016-08-30"
stop_date = "2016-09-15"
num_proc = 12
num_proc4topo = 12
